workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: windows_x2

        triggering:
            events:                      
                - push

        cache:
            cache_paths:
                - ~/.gradle/caches

        environment:
            java: 2
            android_signing:
                - codemagic
            vars:
                PACKAGE_NAME: "com.exam.codemagichelloworldandroid"

        scripts:
            - name: Set Android SDK location
              script: | 
                  echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
            - name: Build Android release
              script: | 
                  ./gradlew bundleRelease

        artifacts:
            - app/build/outputs/**/*.aab

        publishing:
            slack:
                channel: '#codemagic-hello-world-stack'
                notify_on_build_start: true
                notify:
                    success: false
                    failure: false


